const DEMO_EMAIL_DOMAIN = "syncup.demo";
const DEMO_PASSWORD = "DemoPass123!";

const languages = [
  { name: "English", code: "en" },
  { name: "Serbian", code: "sr" },
  { name: "German", code: "de" },
  { name: "Spanish", code: "es" },
  { name: "French", code: "fr" },
  { name: "Italian", code: "it" },
  { name: "Korean", code: "ko" },
  { name: "Japanese", code: "ja" },
  { name: "Chinese", code: "zh" },
];

const interests = [
  "Hiking",
  "Coffee",
  "Movies",
  "Fitness",
  "Photography",
  "Travel",
  "Coding",
  "Gaming",
  "Language Exchange",
  "Study Groups",
  "Board Games",
  "Basketball",
  "Music",
  "Design",
];

const vibeTags = [
  "Easygoing",
  "Curious",
  "Funny",
  "Creative",
  "Outdoorsy",
  "Focused",
  "Late-night planner",
  "Calm energy",
  "Social but chill",
  "Competitive",
  "Thoughtful",
  "Weekend explorer",
];

const activityCategories = [
  "Hikes",
  "Coffee Runs",
  "Movie Nights",
  "Basketball",
  "Board Games",
  "Study Sessions",
  "Language Practice",
  "Photo Walks",
  "Gym Meetups",
  "Coding Sessions",
];

const userArchetypes = [
  {
    firstName: "Mila",
    lastName: "Petrovic",
    username: "mila.walks",
    bio: "Coffee, easy hikes, and sunset photos.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Hiking", "Coffee", "Photography"],
    vibeTags: ["Easygoing", "Outdoorsy", "Weekend explorer"],
    activityCategories: ["Hikes", "Coffee Runs", "Photo Walks"],
    activityLevel: "high",
  },
  {
    firstName: "Stefan",
    lastName: "Jovanic",
    username: "stefcodes",
    bio: "Building side projects and pretending bugs are features.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "ONLINE_GAMING",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Coding", "Gaming", "Coffee"],
    vibeTags: ["Focused", "Funny", "Late-night planner"],
    activityCategories: ["Coding Sessions", "Coffee Runs"],
    activityLevel: "high",
  },
  {
    firstName: "Lena",
    lastName: "Markovic",
    username: "lenalens",
    bio: "Street photos, film nights, and random city walks.",
    city: "Novi Sad",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Photography", "Movies", "Travel"],
    vibeTags: ["Creative", "Curious", "Calm energy"],
    activityCategories: ["Photo Walks", "Movie Nights"],
    activityLevel: "medium",
  },
  {
    firstName: "Nikola",
    lastName: "Savic",
    username: "nikfit",
    bio: "Gym, football, and always down for weekend plans.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "GROUP_HANGOUTS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Fitness", "Basketball", "Travel"],
    vibeTags: ["Competitive", "Social but chill", "Weekend explorer"],
    activityCategories: ["Gym Meetups", "Basketball", "Hikes"],
    activityLevel: "high",
  },
  {
    firstName: "Sara",
    lastName: "Ilic",
    username: "sara.studies",
    bio: "Student life, good playlists, and late coffee runs.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Study Groups", "Coffee", "Music"],
    vibeTags: ["Thoughtful", "Calm energy", "Easygoing"],
    activityCategories: ["Study Sessions", "Coffee Runs"],
    activityLevel: "medium",
  },
  {
    firstName: "Vuk",
    lastName: "Radic",
    username: "vuk.boards",
    bio: "Board games, bad jokes, and way too competitive.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "GROUP_HANGOUTS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Board Games", "Movies", "Coffee"],
    vibeTags: ["Funny", "Competitive", "Social but chill"],
    activityCategories: ["Board Games", "Movie Nights", "Coffee Runs"],
    activityLevel: "high",
  },
  {
    firstName: "Ana",
    lastName: "Kovacevic",
    username: "ana.abroad",
    bio: "Languages, travel plans, and finding cheap flights.",
    city: "Novi Sad",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English", "Spanish"],
    interests: ["Language Exchange", "Travel", "Coffee"],
    vibeTags: ["Curious", "Easygoing", "Weekend explorer"],
    activityCategories: ["Language Practice", "Coffee Runs"],
    activityLevel: "medium",
  },
  {
    firstName: "Teodora",
    lastName: "Milic",
    username: "teo.movies",
    bio: "Reviews nobody asked for.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Movies", "Coffee", "Music"],
    vibeTags: ["Thoughtful", "Funny", "Calm energy"],
    activityCategories: ["Movie Nights", "Coffee Runs"],
    activityLevel: "medium",
  },
  {
    firstName: "Marko",
    lastName: "Zivkovic",
    username: "markoontrail",
    bio: "Beginner hikes, nature, and weekend escapes.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Hiking", "Travel", "Photography"],
    vibeTags: ["Outdoorsy", "Calm energy", "Weekend explorer"],
    activityCategories: ["Hikes", "Photo Walks"],
    activityLevel: "medium",
  },
  {
    firstName: "Nina",
    lastName: "Pavlov",
    username: "nina.pixel",
    bio: "Design, cameras, and saving places I'll probably visit.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Design", "Photography", "Travel"],
    vibeTags: ["Creative", "Curious", "Thoughtful"],
    activityCategories: ["Photo Walks", "Coffee Runs"],
    activityLevel: "medium",
  },
  {
    firstName: "Petar",
    lastName: "Ristic",
    username: "petar.pickup",
    bio: "Casual hoops, city walks, and one more coffee than necessary.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "GROUP_HANGOUTS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Basketball", "Coffee", "Travel"],
    vibeTags: ["Social but chill", "Competitive", "Easygoing"],
    activityCategories: ["Basketball", "Coffee Runs"],
    activityLevel: "high",
  },
  {
    firstName: "Jelena",
    lastName: "Stanic",
    username: "jela.coffee",
    bio: "Always rating cafes by chairs, playlists, and window light.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English", "Italian"],
    interests: ["Coffee", "Design", "Photography"],
    vibeTags: ["Creative", "Easygoing", "Calm energy"],
    activityCategories: ["Coffee Runs", "Photo Walks"],
    activityLevel: "medium",
  },
  {
    firstName: "Ognjen",
    lastName: "Djukic",
    username: "ogidbg",
    bio: "Junior dev. Good at debugging other people's code, less my own.",
    city: "Novi Sad",
    country: "Serbia",
    socialMode: "ONLINE_GAMING",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Coding", "Gaming", "Movies"],
    vibeTags: ["Focused", "Funny", "Thoughtful"],
    activityCategories: ["Coding Sessions", "Movie Nights"],
    activityLevel: "medium",
  },
  {
    firstName: "Dunja",
    lastName: "Lazic",
    username: "dunja.frames",
    bio: "Mostly outside for the light, sometimes for the people.",
    city: "Nis",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Photography", "Travel", "Coffee"],
    vibeTags: ["Creative", "Calm energy", "Outdoorsy"],
    activityCategories: ["Photo Walks", "Coffee Runs"],
    activityLevel: "low",
  },
  {
    firstName: "Filip",
    lastName: "Matic",
    username: "filip.flex",
    bio: "Early gym, late dinner, somehow still tired.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "GROUP_HANGOUTS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Fitness", "Basketball", "Music"],
    vibeTags: ["Competitive", "Social but chill", "Focused"],
    activityCategories: ["Gym Meetups", "Basketball"],
    activityLevel: "medium",
  },
  {
    firstName: "Ivana",
    lastName: "Bogdanovic",
    username: "ivana.words",
    bio: "Trying to keep my French alive and my calendar under control.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English", "French"],
    interests: ["Language Exchange", "Travel", "Study Groups"],
    vibeTags: ["Thoughtful", "Curious", "Focused"],
    activityCategories: ["Language Practice", "Study Sessions"],
    activityLevel: "low",
  },
  {
    firstName: "Luka",
    lastName: "Peric",
    username: "luka.launches",
    bio: "Small products, big to-do lists, and way too many tabs open.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "ONLINE_GAMING",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Coding", "Design", "Coffee"],
    vibeTags: ["Focused", "Creative", "Late-night planner"],
    activityCategories: ["Coding Sessions", "Coffee Runs"],
    activityLevel: "high",
  },
  {
    firstName: "Marija",
    lastName: "Popovic",
    username: "mari.movienotes",
    bio: "If it's slow and a little sad, I probably loved it.",
    city: "Novi Sad",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Movies", "Music", "Coffee"],
    vibeTags: ["Thoughtful", "Calm energy", "Creative"],
    activityCategories: ["Movie Nights", "Coffee Runs"],
    activityLevel: "low",
  },
  {
    firstName: "Boris",
    lastName: "Knezevic",
    username: "boris.weekend",
    bio: "Usually organizing plans I pretend will stay low-key.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "GROUP_HANGOUTS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English"],
    interests: ["Board Games", "Travel", "Coffee"],
    vibeTags: ["Social but chill", "Funny", "Weekend explorer"],
    activityCategories: ["Board Games", "Coffee Runs", "Hikes"],
    activityLevel: "high",
  },
  {
    firstName: "Katarina",
    lastName: "Milenkovic",
    username: "kat.studybreak",
    bio: "Study sessions first, dessert after.",
    city: "Belgrade",
    country: "Serbia",
    socialMode: "JUST_CHAT",
    visibility: "PUBLIC",
    languages: ["Serbian", "English", "German"],
    interests: ["Study Groups", "Coffee", "Language Exchange"],
    vibeTags: ["Focused", "Easygoing", "Thoughtful"],
    activityCategories: ["Study Sessions", "Language Practice", "Coffee Runs"],
    activityLevel: "medium",
  },
  {
    firstName: "Andrej",
    lastName: "Vasic",
    username: "andrej.roam",
    bio: "Cheap train rides, cameras, and saying yes to random plans.",
    city: "Nis",
    country: "Serbia",
    socialMode: "REAL_LIFE_MEETUPS",
    visibility: "PUBLIC",
    languages: ["Serbian", "English", "Spanish"],
    interests: ["Travel", "Photography", "Language Exchange"],
    vibeTags: ["Curious", "Weekend explorer", "Social but chill"],
    activityCategories: ["Photo Walks", "Language Practice", "Hikes"],
    activityLevel: "medium",
  },
];

const communities = [
  {
    name: "Belgrade Hike Crew",
    slug: "belgrade-hike-crew",
    description: "Easygoing local hikes, beginner-friendly routes, and a group chat full of weather checks.",
    city: "Belgrade",
    country: "Serbia",
    category: "Outdoors",
    ownerUsername: "mila.walks",
    interests: ["Hiking", "Travel", "Photography"],
    vibeTags: ["Outdoorsy", "Easygoing", "Weekend explorer"],
  },
  {
    name: "Sunday Coffee Club",
    slug: "sunday-coffee-club",
    description: "Cafe picks, quiet laptop spots, and casual meetups around the city.",
    city: "Belgrade",
    country: "Serbia",
    category: "Lifestyle",
    ownerUsername: "jela.coffee",
    interests: ["Coffee", "Design", "Study Groups"],
    vibeTags: ["Calm energy", "Easygoing", "Social but chill"],
  },
  {
    name: "Movie Nights",
    slug: "movie-nights",
    description: "Weekly watch picks, tiny reviews, and last-minute cinema plans.",
    city: "Belgrade",
    country: "Serbia",
    category: "Entertainment",
    ownerUsername: "teo.movies",
    interests: ["Movies", "Music", "Coffee"],
    vibeTags: ["Thoughtful", "Funny", "Calm energy"],
  },
  {
    name: "Coding After Hours",
    slug: "coding-after-hours",
    description: "Side projects, accountability sprints, and shipping something small every month.",
    city: "Belgrade",
    country: "Serbia",
    category: "Tech",
    ownerUsername: "stefcodes",
    interests: ["Coding", "Design", "Coffee"],
    vibeTags: ["Focused", "Creative", "Late-night planner"],
  },
  {
    name: "Photo Walks Serbia",
    slug: "photo-walks-serbia",
    description: "Street shots, sunset sessions, and editing tips from people who actually go outside.",
    city: "Novi Sad",
    country: "Serbia",
    category: "Creative",
    ownerUsername: "lenalens",
    interests: ["Photography", "Travel", "Design"],
    vibeTags: ["Creative", "Curious", "Outdoorsy"],
  },
  {
    name: "Language Exchange Corner",
    slug: "language-exchange-corner",
    description: "Casual speaking practice for anyone switching between Serbian, English, and more.",
    city: "Belgrade",
    country: "Serbia",
    category: "Learning",
    ownerUsername: "ana.abroad",
    interests: ["Language Exchange", "Travel", "Study Groups"],
    vibeTags: ["Curious", "Thoughtful", "Easygoing"],
  },
  {
    name: "Casual Hoops",
    slug: "casual-hoops",
    description: "Low-pressure 3v3 and 5v5 runs for people who want games without the drama.",
    city: "Belgrade",
    country: "Serbia",
    category: "Sports",
    ownerUsername: "petar.pickup",
    interests: ["Basketball", "Fitness", "Travel"],
    vibeTags: ["Competitive", "Social but chill", "Weekend explorer"],
  },
  {
    name: "Board Game Evenings",
    slug: "board-game-evenings",
    description: "Midweek games, good snacks, and friendly arguments over rules.",
    city: "Belgrade",
    country: "Serbia",
    category: "Games",
    ownerUsername: "vuk.boards",
    interests: ["Board Games", "Coffee", "Movies"],
    vibeTags: ["Funny", "Competitive", "Social but chill"],
  },
];

const directMessagePlans = [
  {
    pair: ["mila.walks", "sara.studies"],
    messages: [
      "Are you still up for a coffee before the study session tomorrow?",
      "Yes please. I need caffeine before I look at my notes again.",
      "Same. Want to try the place near Studentski Park?",
      "Perfect. I'll be there around 4:30.",
    ],
  },
  {
    pair: ["stefcodes", "luka.launches"],
    messages: [
      "Did you end up fixing that auth bug?",
      "Mostly. It was one line and two hours of confusion.",
      "Classic. Want to cowork Thursday night?",
      "Yes, if we also allow snacks and complaining.",
      "That's basically the whole plan.",
    ],
  },
  {
    pair: ["lenalens", "dunja.frames"],
    messages: [
      "Your last set from Zemun looked really good.",
      "Thank you. The light did half the work.",
      "Photo walk this weekend if the weather holds?",
      "I'm in. Sunset timing again?",
      "Obviously.",
    ],
  },
  {
    pair: ["teo.movies", "mari.movienotes"],
    messages: [
      "Need a second opinion. Was that ending great or just confusing?",
      "A little of both, which is why I liked it.",
      "Okay good, I thought I was being too generous.",
      "Never. We're simply correct.",
    ],
  },
  {
    pair: ["vuk.boards", "boris.weekend"],
    messages: [
      "Need one more person for board games tonight.",
      "What are we playing?",
      "Probably Codenames and then something longer if people stay.",
      "I'm in if nobody minds me getting too competitive.",
      "That is literally the brand.",
    ],
  },
  {
    pair: ["ana.abroad", "ivana.words"],
    messages: [
      "Would you be up for a French-English swap next week?",
      "Yes, please. My French is rusty but alive.",
      "Perfect. Mine too, honestly.",
      "That makes it less intimidating already.",
    ],
  },
  {
    pair: ["petar.pickup", "nikfit"],
    messages: [
      "Court at 8 tonight?",
      "Yes. We still need one more.",
      "I'll ask Filip.",
      "Do it. I want a full run this time.",
    ],
  },
];

const communityChatPlans = [
  {
    communitySlug: "belgrade-hike-crew",
    entries: [
      ["mila.walks", "Weather looks decent for Saturday. Avala still the plan?"],
      ["markoontrail", "I'm in if we keep the pace beginner-friendly."],
      ["mila.walks", "Definitely. Easy route and coffee after."],
      ["andrej.roam", "Coffee after is the real selling point."],
      ["nikfit", "What time are we meeting?"],
      ["mila.walks", "9:15 at the usual bus stop."],
    ],
  },
  {
    communitySlug: "coding-after-hours",
    entries: [
      ["stefcodes", "Anyone doing a cowork session this week?"],
      ["luka.launches", "Thursday works for me after 7."],
      ["ogidbg", "Same. I'm bringing a half-finished side project and zero confidence."],
      ["stefcodes", "Perfect fit for this community then."],
      ["nina.pixel", "I'll come if someone wants to sanity-check a landing page."],
    ],
  },
  {
    communitySlug: "movie-nights",
    entries: [
      ["teo.movies", "Need a vote: cinema on Friday or apartment movie night on Saturday?"],
      ["mari.movienotes", "Saturday. I want pause-button freedom."],
      ["vuk.boards", "Also snacks cost less at home, which matters."],
      ["teo.movies", "Very strong argument."],
      ["sara.studies", "Saturday works better for me too."],
    ],
  },
  {
    communitySlug: "language-exchange-corner",
    entries: [
      ["ana.abroad", "Thinking of splitting the next meetup into small language tables."],
      ["ivana.words", "That would make speaking way less awkward."],
      ["kat.studybreak", "Can we have a beginner-friendly corner too?"],
      ["ana.abroad", "Absolutely. No speed-speaking allowed."],
      ["andrej.roam", "Bless this policy."],
    ],
  },
  {
    communitySlug: "board-game-evenings",
    entries: [
      ["vuk.boards", "Reminder: no disappearing after one round tonight."],
      ["boris.weekend", "Rude. Sometimes I leave because I'm losing with dignity."],
      ["mila.walks", "That's not how dignity works."],
      ["vuk.boards", "See everyone at 8."],
    ],
  },
];

module.exports = {
  DEMO_EMAIL_DOMAIN,
  DEMO_PASSWORD,
  activityCategories,
  communities,
  communityChatPlans,
  directMessagePlans,
  interests,
  languages,
  userArchetypes,
  vibeTags,
};
